### PR TITLE
Pressing the just pressed button again is in effect an undo

### LINKED ISSUE #47: Allow the user to undo a move by pressing the button again
It's easier to undo a move by pressing the same button again. This enhancement should apply to the recorded moves as well.

For example, the user presses Buttons 1, 3, 5, and 6. The last move can be undone by pressing Button 6 again (before pressing any other buttons). If the user steps back to the Button 3 move and then press Button 3 again, the recorded moves will only include the Button 1 move.

### PR DESCRIPTION
**Pull request by owenca**
This enhancement also applies to the recorded moves.

Fixes #47

### CODE REVIEW

**Comment by owenca** [comment]
This is the final touch before the GUI redesign (including using the layout management) and localization. A release ( Version 1.0 or 1.1) is in order now? (The *How to play* page and `README.md` need an update to include all the new features.)

**Comment by humdingerb** [comment]
> A release ( Version 1.0 or 1.1) is in order now?

Your call. If you don't expect the GUI redesign being delayed for many weeks or you running out of free time, it may make a bigger splash to aim right for the v2.0 with all bells and whistles.
But, as said, your call, all's fine by me.

**Comment by owenca** [comment]
I won't be able to spend much time on LightsOff for a few weeks. If releasing a 1.x now would get more people to play the game and provide feedback, it might be worth it. Otherwise, we should wait until the GUI gets a facelift, which requires more of your expertise than mine. (I can still code your design, though.)

**Comment by humdingerb** [comment]
I think we could release a little point release, without updating documentation etc. just so your fixes get out. You know, that the puzzles are actually solvable... :)
Then doing a nice 2.0 with a polished GUI, docs, nice sounds later. I guess I'll revert to the old icon too, and save that for 2.0 as the icon is so visible.

**Pull request merged**
